//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public long supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_code { get; set; }
        public Nullable<long> supplier_type_id { get; set; }
        public string company_address { get; set; }
        public string factory_address { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string contact_person { get; set; }
        public Nullable<decimal> total_debit { get; set; }
        public Nullable<decimal> total_credit { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string vat_id { get; set; }
        public string tin_no { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string contact_person2 { get; set; }
        public string email2 { get; set; }
        public string receiving_company_name { get; set; }
        public string receiving_company_person { get; set; }
        public string receiving_company_contact_email { get; set; }
    }
}
