//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_details
    {
        public long delivery_details_id { get; set; }
        public Nullable<long> delivery_master_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<long> color_id { get; set; }
        public Nullable<long> product_version_id { get; set; }
        public Nullable<long> party_id { get; set; }
        public Nullable<int> requisition_quantity { get; set; }
        public Nullable<int> delivered_quantity { get; set; }
        public Nullable<bool> is_gift { get; set; }
        public Nullable<bool> is_live_dummy { get; set; }
        public string gift_type { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> line_total { get; set; }
    }
}
