//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class party
    {
        public long party_id { get; set; }
        public string party_name { get; set; }
        public string address { get; set; }
        public string proprietor_name { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<long> party_type_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public string gl_account { get; set; }
        public string party_code { get; set; }
        public Nullable<long> parent_party_id { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> province_id { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<long> zone_id { get; set; }
        public Nullable<long> area_id { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> territory_id { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<long> dealer_type_id { get; set; }
        public Nullable<long> retailer_type_id { get; set; }
    }
}
