//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order_master
    {
        public long purchase_order_master_id { get; set; }
        public string order_no { get; set; }
        public string purchase_order_reference_number { get; set; }
        public string pi_number { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string shipping_term { get; set; }
        public string shipping_method { get; set; }
        public Nullable<long> shipping_terms_id { get; set; }
        public Nullable<long> shipping_method_id { get; set; }
        public Nullable<long> currency_id { get; set; }
        public string status { get; set; }
        public string terms_n_condition { get; set; }
        public string pi_terms_n_condition { get; set; }
        public string remarks { get; set; }
        public Nullable<long> company_id { get; set; }
        public Nullable<System.DateTime> expected_shipment_date { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public Nullable<decimal> vat_total { get; set; }
        public Nullable<decimal> tax_total { get; set; }
        public Nullable<decimal> total_amount_without_vattax { get; set; }
        public Nullable<decimal> total_amount_including_vattax { get; set; }
        public Nullable<long> batch_id { get; set; }
        public string lc_number { get; set; }
        public string noc_number { get; set; }
        public string pi_attachment_location { get; set; }
        public string verify_status { get; set; }
        public string approve_status { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
