//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eshop_cutomer_requisition_mapping
    {
        public long eshop_cutomer_requisition_mapping_id { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public Nullable<long> requisition_master_id { get; set; }
        public string customer_name { get; set; }
        public string mobile_no { get; set; }
        public string customer_email { get; set; }
        public Nullable<long> shipping { get; set; }
        public Nullable<long> payment_method { get; set; }
        public string shipping_address { get; set; }
        public string billing_address { get; set; }
    }
}
