//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eshop_return_details
    {
        public long eshop_return_details_id { get; set; }
        public Nullable<long> eshop_return_master_id { get; set; }
        public Nullable<long> brand_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> color_id { get; set; }
        public Nullable<long> product_version_id { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<int> returned_qty { get; set; }
        public Nullable<decimal> price { get; set; }
        public string imei_no { get; set; }
        public string imei_no2 { get; set; }
        public Nullable<bool> verify_status { get; set; }
        public Nullable<System.DateTime> verify_date { get; set; }
        public Nullable<long> warehouse_id { get; set; }
    }
}
