//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grn_details
    {
        public long grn_details_id { get; set; }
        public Nullable<long> grn_master_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> brand_id { get; set; }
        public Nullable<long> color_id { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<long> size_id { get; set; }
        public Nullable<long> product_version_id { get; set; }
        public Nullable<int> pi_quantity { get; set; }
        public Nullable<int> receive_quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> vat_pcnt { get; set; }
        public Nullable<decimal> tax_pcnt { get; set; }
        public Nullable<decimal> vat_amount { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> line_total { get; set; }
        public Nullable<decimal> amount { get; set; }
    }
}
