//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrr_details
    {
        public long mrr_details_id { get; set; }
        public Nullable<long> mrr_master_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> color_id { get; set; }
        public Nullable<long> product_version_id { get; set; }
        public Nullable<int> grn_quantity { get; set; }
        public Nullable<int> saleable_quantity { get; set; }
        public Nullable<int> box_damage_quantity { get; set; }
        public Nullable<int> physical_damaged_quantity { get; set; }
        public Nullable<int> customs_lost_quantity { get; set; }
        public Nullable<int> total_received_quantity { get; set; }
    }
}
