//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion_master
    {
        public long promotion_master_id { get; set; }
        public string promotion_code { get; set; }
        public string promotion_name { get; set; }
        public Nullable<System.DateTime> promotion_start_date { get; set; }
        public Nullable<System.DateTime> promotion_end_date { get; set; }
        public Nullable<long> product_category_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<int> lifting_quantity_for_promotion { get; set; }
        public string promotion_type { get; set; }
        public Nullable<decimal> promotion_discount { get; set; }
        public Nullable<bool> is_discount_percent { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
