//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class return_master
    {
        public long return_master_id { get; set; }
        public string return_code { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<long> return_type { get; set; }
        public Nullable<long> party_id { get; set; }
        public string remarks { get; set; }
        public Nullable<long> doa_warehouse_id { get; set; }
        public string doa_varify_status { get; set; }
        public Nullable<System.DateTime> doa_verified_date { get; set; }
        public Nullable<long> doa_verified_by { get; set; }
        public string doa_receive_status { get; set; }
        public Nullable<long> doa_received_by { get; set; }
        public Nullable<System.DateTime> doa_receive_date { get; set; }
        public Nullable<int> returned_quantity { get; set; }
        public Nullable<long> returned_by { get; set; }
        public Nullable<long> invoice_master_id { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
