//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public long employee_id { get; set; }
        public string employee_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<System.DateTime> date_of_join { get; set; }
        public Nullable<long> department_id { get; set; }
        public Nullable<long> designation_id { get; set; }
        public string email_address { get; set; }
        public string mobile_number { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public string marital_status { get; set; }
        public string blood_group { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> area_id { get; set; }
        public Nullable<long> territory_id { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
