//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrr_master
    {
        public long mrr_master_id { get; set; }
        public string mrr_no { get; set; }
        public Nullable<long> grn_master_id { get; set; }
        public string lost_comment { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> from_warehouse_id { get; set; }
    }
}
