//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public long product_id { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public Nullable<long> product_category_id { get; set; }
        public Nullable<long> brand_id { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<decimal> current_balance { get; set; }
        public string product_image_url { get; set; }
        public Nullable<bool> has_serial { get; set; }
        public Nullable<bool> has_warrenty { get; set; }
        public string warrenty_type { get; set; }
        public Nullable<decimal> warrenty_value { get; set; }
        public Nullable<decimal> vat_percentage { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<decimal> rp_price { get; set; }
        public Nullable<decimal> mrp_price { get; set; }
        public Nullable<decimal> md_price { get; set; }
        public Nullable<decimal> bs_price { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public Nullable<System.DateTime> eol_date { get; set; }
        public string remarks { get; set; }
        public string specification { get; set; }
        public Nullable<System.DateTime> launce_date { get; set; }
        public Nullable<long> accessories_category_id { get; set; }
    }
}
