//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion_details
    {
        public long promotion_details_id { get; set; }
        public Nullable<long> promotion_master_id { get; set; }
        public Nullable<long> product_category_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<int> gift_quantity { get; set; }
    }
}
