//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class terms_and_condition
    {
        public long terms_and_condition_id { get; set; }
        public string terms_and_condition_description { get; set; }
        public string terms_condition_header { get; set; }
        public bool is_active { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<long> updated_by { get; set; }
    }
}
