//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ci_pl_details
    {
        public long ci_pl_details_id { get; set; }
        public Nullable<long> ci_pl_master_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> nw_kg_ctn { get; set; }
        public Nullable<decimal> gw_kg_ctn { get; set; }
        public Nullable<decimal> measurement { get; set; }
    }
}
