//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class control
    {
        public long control_id { get; set; }
        public string control_name { get; set; }
        public Nullable<long> control_parent_id { get; set; }
        public Nullable<long> control_type_id { get; set; }
        public Nullable<long> control_sort { get; set; }
        public string control_alias { get; set; }
        public string control_controller { get; set; }
        public string control_action { get; set; }
        public Nullable<long> company_id { get; set; }
        public Nullable<long> Level { get; set; }
        public string icon { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<long> Territory_id { get; set; }
        public Nullable<long> region_id { get; set; }
    }
}
