//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class designation
    {
        public long sales_designation_id { get; set; }
        public Nullable<long> parent_designation_id { get; set; }
        public Nullable<long> designation_id { get; set; }
        public Nullable<long> sales_type_id { get; set; }
        public string sales_designation { get; set; }
        public string sales_person_type_code { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
