//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grn_master
    {
        public long grn_master_id { get; set; }
        public string grn_no { get; set; }
        public Nullable<long> supplier_id { get; set; }
        public Nullable<long> purchase_order_master_id { get; set; }
        public Nullable<long> lc_id { get; set; }
        public Nullable<long> warehouse_id { get; set; }
        public Nullable<System.DateTime> grn_date { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
        public Nullable<long> company_id { get; set; }
        public string lot_no { get; set; }
        public Nullable<decimal> vat_total { get; set; }
        public Nullable<decimal> tax_total { get; set; }
        public Nullable<decimal> total_amount_without_vattax { get; set; }
        public Nullable<decimal> total_amount_including_vattax { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<bool> mrr_status { get; set; }
    }
}
