//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class internal_requisition_master
    {
        public long internal_requisition_master_id { get; set; }
        public string internal_requisition_no { get; set; }
        public string customar_name { get; set; }
        public string mobile_no { get; set; }
        public string pricing { get; set; }
        public string payment_type { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<long> from_warehouse_id { get; set; }
        public Nullable<long> to_department { get; set; }
        public Nullable<System.DateTime> requisition_date { get; set; }
        public string remarks { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string requisition_status { get; set; }
        public Nullable<int> no_of_installments { get; set; }
        public Nullable<System.DateTime> first_installment_date { get; set; }
        public Nullable<decimal> total_incentive_amount { get; set; }
    }
}
