//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_price_mapping_log
    {
        public long product_price_mapping_log_id { get; set; }
        public Nullable<long> product_price_mapping_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<long> product_version_id { get; set; }
        public Nullable<long> color_id { get; set; }
        public Nullable<decimal> dealer_cost { get; set; }
        public Nullable<decimal> b2b_cost { get; set; }
        public Nullable<decimal> telco_cost { get; set; }
        public Nullable<decimal> corporate_cost { get; set; }
        public Nullable<decimal> internal_cost { get; set; }
        public Nullable<decimal> online_cost { get; set; }
        public Nullable<decimal> gift_cost { get; set; }
        public Nullable<decimal> emi_cost { get; set; }
        public Nullable<decimal> retailer_cost { get; set; }
        public Nullable<decimal> mrp_cost { get; set; }
        public Nullable<decimal> land_cost { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<decimal> fin_cost { get; set; }
        public Nullable<decimal> price_protection { get; set; }
        public Nullable<decimal> incentive_cost { get; set; }
        public Nullable<decimal> promotional_cost { get; set; }
        public Nullable<decimal> marketing_cost { get; set; }
        public Nullable<decimal> distribution_cost { get; set; }
        public Nullable<decimal> qc_cost { get; set; }
        public Nullable<decimal> we_wifi { get; set; }
        public Nullable<decimal> we_cloud { get; set; }
        public Nullable<decimal> cost_price { get; set; }
        public Nullable<decimal> package_cost { get; set; }
        public Nullable<decimal> total_package_cost { get; set; }
        public Nullable<decimal> amra_margin { get; set; }
        public Nullable<decimal> dealer_margin { get; set; }
        public Nullable<decimal> retailer_margin { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string last_grn_no { get; set; }
    }
}
