//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public long warehouse_id { get; set; }
        public string warehouse_name { get; set; }
        public string warehouse_code { get; set; }
        public string warehouse_address { get; set; }
        public Nullable<long> warehouse_incharge { get; set; }
        public string warehouse_type { get; set; }
        public Nullable<long> party_id { get; set; }
        public Nullable<long> party_type_id { get; set; }
        public Nullable<long> province_id { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<long> region_id { get; set; }
        public Nullable<long> area_id { get; set; }
        public Nullable<long> territory_id { get; set; }
    }
}
