//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_master
    {
        public long invoice_master_id { get; set; }
        public string invoice_no { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<long> party_id { get; set; }
        public Nullable<long> requisition_master_id { get; set; }
        public Nullable<decimal> item_total { get; set; }
        public Nullable<decimal> rebate_total { get; set; }
        public Nullable<decimal> invoice_total { get; set; }
        public Nullable<decimal> account_balance { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> incentive_amount { get; set; }
        public Nullable<decimal> incentive_percentage { get; set; }
        public Nullable<decimal> discount_percentage { get; set; }
        public Nullable<long> pos_master_id { get; set; }
        public Nullable<long> owner_party_id { get; set; }
        public Nullable<long> retailer_delivery_master_id { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> updated_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<long> party_type_id { get; set; }
        public Nullable<System.DateTime> credit_term { get; set; }
        public string contact_person_mobile { get; set; }
        public string address { get; set; }
        public string reference_no { get; set; }
        public string price_type { get; set; }
        public Nullable<long> company_id { get; set; }
        public string sales_head_recommendation { get; set; }
        public string operation_remarks { get; set; }
        public Nullable<decimal> requisition_amount { get; set; }
    }
}
