//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class online_invoice_requisition_mapping
    {
        public long mapping_id { get; set; }
        public Nullable<long> online_invoice_master_id { get; set; }
        public Nullable<long> requisition_master_id { get; set; }
    }
}
